set(_CATKIN_CURRENT_PACKAGE "scan_detect_obstacle")
set(scan_detect_obstacle_VERSION "0.0.0")
set(scan_detect_obstacle_MAINTAINER "ros <ros@todo.todo>")
set(scan_detect_obstacle_PACKAGE_FORMAT "2")
set(scan_detect_obstacle_BUILD_DEPENDS "sensor_msgs" "nav_msgs" "visualization_msgs" "tf" "roscpp")
set(scan_detect_obstacle_BUILD_EXPORT_DEPENDS "roscpp")
set(scan_detect_obstacle_BUILDTOOL_DEPENDS "catkin")
set(scan_detect_obstacle_BUILDTOOL_EXPORT_DEPENDS )
set(scan_detect_obstacle_EXEC_DEPENDS "sensor_msgs" "nav_msgs" "visualization_msgs" "tf" "roscpp")
set(scan_detect_obstacle_RUN_DEPENDS "sensor_msgs" "nav_msgs" "visualization_msgs" "tf" "roscpp")
set(scan_detect_obstacle_TEST_DEPENDS )
set(scan_detect_obstacle_DOC_DEPENDS )
set(scan_detect_obstacle_URL_WEBSITE "")
set(scan_detect_obstacle_URL_BUGTRACKER "")
set(scan_detect_obstacle_URL_REPOSITORY "")
set(scan_detect_obstacle_DEPRECATED "")