// Generated by gencpp from file path_finding/Grid.msg
// DO NOT EDIT!


#ifndef PATH_FINDING_MESSAGE_GRID_H
#define PATH_FINDING_MESSAGE_GRID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace path_finding
{
template <class ContainerAllocator>
struct Grid_
{
  typedef Grid_<ContainerAllocator> Type;

  Grid_()
    : sub_area()
    , done(false)
    , unreachable(false)  {
    }
  Grid_(const ContainerAllocator& _alloc)
    : sub_area()
    , done(false)
    , unreachable(false)  {
  (void)_alloc;
      sub_area.assign( ::geometry_msgs::Point_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::geometry_msgs::Point_<ContainerAllocator> , 4>  _sub_area_type;
  _sub_area_type sub_area;

   typedef uint8_t _done_type;
  _done_type done;

   typedef uint8_t _unreachable_type;
  _unreachable_type unreachable;





  typedef boost::shared_ptr< ::path_finding::Grid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_finding::Grid_<ContainerAllocator> const> ConstPtr;

}; // struct Grid_

typedef ::path_finding::Grid_<std::allocator<void> > Grid;

typedef boost::shared_ptr< ::path_finding::Grid > GridPtr;
typedef boost::shared_ptr< ::path_finding::Grid const> GridConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_finding::Grid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_finding::Grid_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_finding::Grid_<ContainerAllocator1> & lhs, const ::path_finding::Grid_<ContainerAllocator2> & rhs)
{
  return lhs.sub_area == rhs.sub_area &&
    lhs.done == rhs.done &&
    lhs.unreachable == rhs.unreachable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_finding::Grid_<ContainerAllocator1> & lhs, const ::path_finding::Grid_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_finding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_finding::Grid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_finding::Grid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_finding::Grid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_finding::Grid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_finding::Grid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_finding::Grid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_finding::Grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8477af00e98f03fd36c0b55bb90bc58b";
  }

  static const char* value(const ::path_finding::Grid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8477af00e98f03fdULL;
  static const uint64_t static_value2 = 0x36c0b55bb90bc58bULL;
};

template<class ContainerAllocator>
struct DataType< ::path_finding::Grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_finding/Grid";
  }

  static const char* value(const ::path_finding::Grid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_finding::Grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[4] sub_area\n"
"bool done\n"
"bool unreachable\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::path_finding::Grid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_finding::Grid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sub_area);
      stream.next(m.done);
      stream.next(m.unreachable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Grid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_finding::Grid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_finding::Grid_<ContainerAllocator>& v)
  {
    s << indent << "sub_area[]" << std::endl;
    for (size_t i = 0; i < v.sub_area.size(); ++i)
    {
      s << indent << "  sub_area[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.sub_area[i]);
    }
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
    s << indent << "unreachable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.unreachable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FINDING_MESSAGE_GRID_H
