// Generated by gencpp from file path_finding/GridStamped.msg
// DO NOT EDIT!


#ifndef PATH_FINDING_MESSAGE_GRIDSTAMPED_H
#define PATH_FINDING_MESSAGE_GRIDSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <path_finding/GridArray.h>

namespace path_finding
{
template <class ContainerAllocator>
struct GridStamped_
{
  typedef GridStamped_<ContainerAllocator> Type;

  GridStamped_()
    : header()
    , grid()  {
    }
  GridStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , grid(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::path_finding::GridArray_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::path_finding::GridArray_<ContainerAllocator> >> _grid_type;
  _grid_type grid;





  typedef boost::shared_ptr< ::path_finding::GridStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_finding::GridStamped_<ContainerAllocator> const> ConstPtr;

}; // struct GridStamped_

typedef ::path_finding::GridStamped_<std::allocator<void> > GridStamped;

typedef boost::shared_ptr< ::path_finding::GridStamped > GridStampedPtr;
typedef boost::shared_ptr< ::path_finding::GridStamped const> GridStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_finding::GridStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_finding::GridStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_finding::GridStamped_<ContainerAllocator1> & lhs, const ::path_finding::GridStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.grid == rhs.grid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_finding::GridStamped_<ContainerAllocator1> & lhs, const ::path_finding::GridStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_finding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_finding::GridStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_finding::GridStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_finding::GridStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_finding::GridStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_finding::GridStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_finding::GridStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_finding::GridStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb89431ea13652c1ae0d876e69593b78";
  }

  static const char* value(const ::path_finding::GridStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb89431ea13652c1ULL;
  static const uint64_t static_value2 = 0xae0d876e69593b78ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_finding::GridStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_finding/GridStamped";
  }

  static const char* value(const ::path_finding::GridStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_finding::GridStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"path_finding/GridArray[] grid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: path_finding/GridArray\n"
"path_finding/Grid[] grid\n"
"================================================================================\n"
"MSG: path_finding/Grid\n"
"geometry_msgs/Point[4] sub_area\n"
"bool done\n"
"bool unreachable\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::path_finding::GridStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_finding::GridStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.grid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GridStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_finding::GridStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_finding::GridStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "grid[]" << std::endl;
    for (size_t i = 0; i < v.grid.size(); ++i)
    {
      s << indent << "  grid[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::path_finding::GridArray_<ContainerAllocator> >::stream(s, indent + "    ", v.grid[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FINDING_MESSAGE_GRIDSTAMPED_H
