// Generated by gencpp from file path_finding/PoseWasteStamped.msg
// DO NOT EDIT!


#ifndef PATH_FINDING_MESSAGE_POSEWASTESTAMPED_H
#define PATH_FINDING_MESSAGE_POSEWASTESTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <path_finding/PoseWaste.h>

namespace path_finding
{
template <class ContainerAllocator>
struct PoseWasteStamped_
{
  typedef PoseWasteStamped_<ContainerAllocator> Type;

  PoseWasteStamped_()
    : header()
    , data()  {
    }
  PoseWasteStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::path_finding::PoseWaste_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::path_finding::PoseWasteStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_finding::PoseWasteStamped_<ContainerAllocator> const> ConstPtr;

}; // struct PoseWasteStamped_

typedef ::path_finding::PoseWasteStamped_<std::allocator<void> > PoseWasteStamped;

typedef boost::shared_ptr< ::path_finding::PoseWasteStamped > PoseWasteStampedPtr;
typedef boost::shared_ptr< ::path_finding::PoseWasteStamped const> PoseWasteStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_finding::PoseWasteStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_finding::PoseWasteStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_finding::PoseWasteStamped_<ContainerAllocator1> & lhs, const ::path_finding::PoseWasteStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_finding::PoseWasteStamped_<ContainerAllocator1> & lhs, const ::path_finding::PoseWasteStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_finding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_finding::PoseWasteStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_finding::PoseWasteStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_finding::PoseWasteStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_finding::PoseWasteStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_finding::PoseWasteStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_finding::PoseWasteStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_finding::PoseWasteStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fec343c0b056b50bf89033eb229e869c";
  }

  static const char* value(const ::path_finding::PoseWasteStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfec343c0b056b50bULL;
  static const uint64_t static_value2 = 0xf89033eb229e869cULL;
};

template<class ContainerAllocator>
struct DataType< ::path_finding::PoseWasteStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_finding/PoseWasteStamped";
  }

  static const char* value(const ::path_finding::PoseWasteStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_finding::PoseWasteStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"path_finding/PoseWaste data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: path_finding/PoseWaste\n"
"string waste\n"
"geometry_msgs/Point center\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::path_finding::PoseWasteStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_finding::PoseWasteStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseWasteStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_finding::PoseWasteStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_finding::PoseWasteStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::path_finding::PoseWaste_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FINDING_MESSAGE_POSEWASTESTAMPED_H
