// Generated by gencpp from file path_finding/PoseWaste.msg
// DO NOT EDIT!


#ifndef PATH_FINDING_MESSAGE_POSEWASTE_H
#define PATH_FINDING_MESSAGE_POSEWASTE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace path_finding
{
template <class ContainerAllocator>
struct PoseWaste_
{
  typedef PoseWaste_<ContainerAllocator> Type;

  PoseWaste_()
    : waste()
    , center()  {
    }
  PoseWaste_(const ContainerAllocator& _alloc)
    : waste(_alloc)
    , center(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _waste_type;
  _waste_type waste;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;





  typedef boost::shared_ptr< ::path_finding::PoseWaste_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_finding::PoseWaste_<ContainerAllocator> const> ConstPtr;

}; // struct PoseWaste_

typedef ::path_finding::PoseWaste_<std::allocator<void> > PoseWaste;

typedef boost::shared_ptr< ::path_finding::PoseWaste > PoseWastePtr;
typedef boost::shared_ptr< ::path_finding::PoseWaste const> PoseWasteConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_finding::PoseWaste_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_finding::PoseWaste_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_finding::PoseWaste_<ContainerAllocator1> & lhs, const ::path_finding::PoseWaste_<ContainerAllocator2> & rhs)
{
  return lhs.waste == rhs.waste &&
    lhs.center == rhs.center;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_finding::PoseWaste_<ContainerAllocator1> & lhs, const ::path_finding::PoseWaste_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_finding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_finding::PoseWaste_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_finding::PoseWaste_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_finding::PoseWaste_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_finding::PoseWaste_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_finding::PoseWaste_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_finding::PoseWaste_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_finding::PoseWaste_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a4d766ff7efd04002a2333631f161f9";
  }

  static const char* value(const ::path_finding::PoseWaste_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a4d766ff7efd040ULL;
  static const uint64_t static_value2 = 0x02a2333631f161f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_finding::PoseWaste_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_finding/PoseWaste";
  }

  static const char* value(const ::path_finding::PoseWaste_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_finding::PoseWaste_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string waste\n"
"geometry_msgs/Point center\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::path_finding::PoseWaste_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_finding::PoseWaste_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waste);
      stream.next(m.center);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseWaste_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_finding::PoseWaste_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_finding::PoseWaste_<ContainerAllocator>& v)
  {
    s << indent << "waste: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.waste);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_FINDING_MESSAGE_POSEWASTE_H
