# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_finding/GridArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import path_finding.msg

class GridArray(genpy.Message):
  _md5sum = "3dc66829f5cad491c9d9128ab16fff09"
  _type = "path_finding/GridArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """path_finding/Grid[] grid
================================================================================
MSG: path_finding/Grid
geometry_msgs/Point[4] sub_area
bool done
bool unreachable

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['grid']
  _slot_types = ['path_finding/Grid[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       grid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GridArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.grid is None:
        self.grid = []
    else:
      self.grid = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.grid)
      buff.write(_struct_I.pack(length))
      for val1 in self.grid:
        if len(val1.sub_area) != 4:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(val1.sub_area), 'val1.sub_area')))
        for val2 in val1.sub_area:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_2B().pack(_x.done, _x.unreachable))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.grid is None:
        self.grid = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.grid = []
      for i in range(0, length):
        val1 = path_finding.msg.Grid()
        val1.sub_area = []
        for i in range(0, 4):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.sub_area.append(val2)
        _x = val1
        start = end
        end += 2
        (_x.done, _x.unreachable,) = _get_struct_2B().unpack(str[start:end])
        val1.done = bool(val1.done)
        val1.unreachable = bool(val1.unreachable)
        self.grid.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.grid)
      buff.write(_struct_I.pack(length))
      for val1 in self.grid:
        if len(val1.sub_area) != 4:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(val1.sub_area), 'val1.sub_area')))
        for val2 in val1.sub_area:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_2B().pack(_x.done, _x.unreachable))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.grid is None:
        self.grid = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.grid = []
      for i in range(0, length):
        val1 = path_finding.msg.Grid()
        val1.sub_area = []
        for i in range(0, 4):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.sub_area.append(val2)
        _x = val1
        start = end
        end += 2
        (_x.done, _x.unreachable,) = _get_struct_2B().unpack(str[start:end])
        val1.done = bool(val1.done)
        val1.unreachable = bool(val1.unreachable)
        self.grid.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
